### PR TITLE
use of nim_waku_protected_shards instead of nim_waku_protected_topics

### PR DESCRIPTION
**Pull request by Ivansete-status**

### CODE REVIEW

**Comment by Ivansete-status** [comment]
Morning @NagyZoltanPeter !
Notice that we need this PR to be completed and deployed in status fleets before we release the `nwaku-v0.34.0`.

**Review by gabrielmer — APPROVED** [review]
Thank you!

**Comment by apentori** [comment]
Could you give a bit more info please ? 
* Is the current version deployed on both fleet already compatible with the parameter  `nim_waku_protected_shards` ? 
* When should this be deploy on which fleet ? 

Updating the commit have a correct name

**Review by apentori — APPROVED** [review]

**Review by jakubgs — APPROVED** [review]
It appears the change was already made to the role in:

- [`infra-role-nim-waku#3c0cf660`](https://github.com/status-im/infra-role-nim-waku/commit/3c0cf660) - chore: using protected shards instead of topics

Which means that the role is not incompatible with older versions of `nim-waku`. We should coordinate deploying of this to avoid downtime.

**Pull request merged**
